[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.pdo",
  "php82Extensions.pdo_sqlite",
  "php82Extensions.sqlite3",
  "php82Extensions.mbstring",
  "php82Extensions.fileinfo",
  "php82Extensions.gd"
]

[phases.build]
cmds = ["mkdir -p uploads database && php database/seed.php"]

[start]
cmd = "PHP_CLI_SERVER_WORKERS=8 php -S 0.0.0.0:$PORT index.php"
